// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE7eK7tg2pln-gPfqXAZkhIiis5WLSbzk',
    appId: '1:594863575424:web:cdf90d9bfa407c1adef165',
    messagingSenderId: '594863575424',
    projectId: 'postai-3fd3c',
    authDomain: 'postai-3fd3c.firebaseapp.com',
    storageBucket: 'postai-3fd3c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-m7s50oWOxWAoI4FxxyOAUzaHmOy50FI',
    appId: '1:594863575424:android:6e32b0782b987b68def165',
    messagingSenderId: '594863575424',
    projectId: 'postai-3fd3c',
    storageBucket: 'postai-3fd3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPVeIJtzVton8Koar2ClYLC1sKIZVBrc8',
    appId: '1:594863575424:ios:657c0e7cfa5c0f66def165',
    messagingSenderId: '594863575424',
    projectId: 'postai-3fd3c',
    storageBucket: 'postai-3fd3c.appspot.com',
    iosBundleId: 'com.example.postai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPVeIJtzVton8Koar2ClYLC1sKIZVBrc8',
    appId: '1:594863575424:ios:6290adc4320d9e9fdef165',
    messagingSenderId: '594863575424',
    projectId: 'postai-3fd3c',
    storageBucket: 'postai-3fd3c.appspot.com',
    iosBundleId: 'com.example.postai.RunnerTests',
  );
}
